#ifndef CREATEWINPROCESS_H
#define CREATEWINPROCESS_H

BOOL
WINAPI
CreateWinProcess(PLXSS_MESSAGE_PORT_RECEIVE_OBJECT LxReceiveMsg,
                 PLX_CREATE_PROCESS_RESULT ProcResult);

#endif //CREATEWINPROCESS_H
