# Makefile for WslReverse project's Linux files

NAME = LxBusClient
BINDIR = ../bin
CFLAGS = -std=c99 -O2 -m64 -Wall -Wextra

$(NAME):
	$(CC) $(CFLAGS) -o $(BINDIR)/$(NAME) $(NAME).c

clean:
	rm $(BINDIR)/$(NAME)
