#ifndef CREATEWINPROCESS_H
#define CREATEWINPROCESS_H

typedef int BOOL;
typedef struct _LXSS_MESSAGE_PORT_RECEIVE_OBJECT LXSS_MESSAGE_PORT_RECEIVE_OBJECT, *PLXSS_MESSAGE_PORT_RECEIVE_OBJECT;
typedef struct _LX_CREATE_PROCESS_RESULT LX_CREATE_PROCESS_RESULT, *PLX_CREATE_PROCESS_RESULT;

BOOL
CreateWinProcess(PLXSS_MESSAGE_PORT_RECEIVE_OBJECT LxReceiveMsg,
                 PLX_CREATE_PROCESS_RESULT ProcResult);

#endif //CREATEWINPROCESS_H
