#Makefile for simple one file sources
BINDIR = ../bin
CC = gcc
CFLAGS := -ggdb -m64 -Wall

exe:
	$(CC) $(CFLAGS) -o $(BINDIR)/ExtractResource ExtractResource.c
	$(CC) $(CFLAGS) -o $(BINDIR)/SuspendUpgrade SuspendUpgrade.c
